function pVect(b,d){return b[0]*d[1]-b[1]*d[0]}function areCrossSegments(b,d,e,g){var k=[d[0]-b[0],d[1]-b[1]],m=[g[0]-e[0],g[1]-e[1]];g=[g[0]-b[0],g[1]-b[1]];var n=[e[0]-b[0],e[1]-b[1]];d=[d[0]-e[0],d[1]-e[1]];b=[b[0]-e[0],b[1]-e[1]];return 0==pVect(k,m)?!1:0>=pVect(k,g)*pVect(k,n)&&0>=pVect(m,d)*pVect(m,b)?!0:!1}function Feuille(b,d,e){this.x=b;this.y=d;this.value=e}function TreePosition(b,d,e,g,k){this.x=b;this.y=d;this.rad=e;this.width=g;this.height=k}
function Noeud(b,d,e,g,k,m,n,p,q,r,s){this.topLeft=b;this.topRight=d;this.bottomLeft=e;this.bottomRight=g;this.xLeft=k;this.xRight=m;this.yTop=n;this.yBottom=p;this.feuille=q;this.position=r;this.id=s;this.ajouterFeuille=function(a){if(null!=this.feuille){var c=this.feuille;this.feuille=null;this.ajouterFeuille(c);this.ajouterFeuille(a)}else{var c=Math.round((this.xLeft+this.xRight)/2),b=Math.round((this.yTop+this.yBottom)/2);a.x<c?a.y<b?null==this.topLeft?this.topLeft=new Noeud(null,null,null,null,
this.xLeft,c,this.yTop,b,a,this.position,this.id):this.topLeft.ajouterFeuille(a):null==this.bottomLeft?this.bottomLeft=new Noeud(null,null,null,null,this.xLeft,c,b,this.yBottom,a,this.position,this.id):this.bottomLeft.ajouterFeuille(a):a.y<b?null==this.topRight?this.topRight=new Noeud(null,null,null,null,c,this.xRight,this.yTop,b,a,this.position,this.id):this.topRight.ajouterFeuille(a):null==this.bottomRight?this.bottomRight=new Noeud(null,null,null,null,c,this.xRight,b,this.yBottom,a,this.position,
this.id):this.bottomRight.ajouterFeuille(a)}};this.getChilds=function(){var a=[];null!=this.topLeft&&a.push(this.topLeft);null!=this.topRight&&a.push(this.topRight);null!=this.bottomLeft&&a.push(this.bottomLeft);null!=this.bottomRight&&a.push(this.bottomRight);return a};this.compress=function(){if(null==this.feuille){var a=this.getChilds();if(0<a.length){for(var c=0;c<a.length;c++)a[c].compress();for(var b=!0,c=0;c<a.length;c++)null==a[c].feuille&&(b=!1);if(b){for(var c=a[0].feuille.value,l=1;l<a.length;l++)a[l].feuille.value!=
c&&(b=!1);b&&(this.bottomRight=this.bottomLeft=this.topRight=this.topLeft=null,this.feuille=new Feuille(-1,-1,c))}}}};this.compterFeuilles=function(){if(null!=this.feuille)return 1;for(var a=this.getChilds(),c=0,b=0;b<a.length;b++)c+=a[b].compterFeuilles();return c};this.getTransformedPoints=function(){var a=Math.cos(this.position.rad),c=Math.sin(this.position.rad),b=this.xLeft-this.position.width/2,l=this.xRight-this.position.width/2,d=this.yTop-this.position.height/2,e=this.yBottom-this.position.height/
2;return[[a*b-c*d+this.position.x+this.position.width/2,c*b+a*d+this.position.y+this.position.height/2],[a*b-c*e+this.position.x+this.position.width/2,c*b+a*e+this.position.y+this.position.height/2],[a*l-c*e+this.position.x+this.position.width/2,c*l+a*e+this.position.y+this.position.height/2],[a*l-c*d+this.position.x+this.position.width/2,c*l+a*d+this.position.y+this.position.height/2]]};this.isInContactWith=function(a){var c=this.getTransformedPoints();a=a.getTransformedPoints();for(var b=[[c[1][0]-
c[0][0],c[1][1]-c[0][1]],[c[2][0]-c[1][0],c[2][1]-c[1][1]],[c[3][0]-c[2][0],c[3][1]-c[2][1]],[c[0][0]-c[3][0],c[0][1]-c[3][1]]],d=[[a[1][0]-a[0][0],a[1][1]-a[0][1]],[a[2][0]-a[1][0],a[2][1]-a[1][1]],[a[3][0]-a[2][0],a[3][1]-a[2][1]],[a[0][0]-a[3][0],a[0][1]-a[3][1]]],e,g,h=0;4>h;h++){g=!0;for(var f=0;4>f;f++)if(e=[a[h][0]-c[f][0],a[h][1]-c[f][1]],0<b[f][0]*e[1]-b[f][1]*e[0]){g=!1;break}if(g)return!0}for(h=0;4>h;h++){g=!0;for(f=0;4>f;f++)if(e=[c[h][0]-a[f][0],c[h][1]-a[f][1]],0<d[f][0]*e[1]-d[f][1]*
e[0]){g=!1;break}if(g)return!0}for(h=0;4>h;h++)for(f=0;4>f;f++)if(areCrossSegments(c[h],c[(h+1)%4],a[f],a[(f+1)%4]))return!0;return!1};this.isCollisionWithNode=function(a){if(null!=this.feuille&&0==this.feuille.value||null!=a.feuille&&0==a.feuille.value||!this.isInContactWith(a))return!1;if(null!=this.feuille&&null!=a.feuille)return!0;var c,b;if(null==this.feuille&null==a.feuille){b=this.getChilds();a=a.getChilds();c=!1;for(var d=0;d<b.length;d++)for(var e=0;e<a.length;e++)b[d].isCollisionWithNode(a[e])&&
(c=!0);return c}if(null==this.feuille){b=this.getChilds();c=!1;for(d=0;d<b.length;d++)a.isCollisionWithNode(b[d])&&(c=!0);return c}a=a.getChilds();c=!1;for(d=0;d<a.length;d++)this.isCollisionWithNode(a[d])&&(c=!0);return c}}var cptId=0;
function CollisionDetector(b){if(b.complete){this.canvas=document.createElement("canvas");this.canvas.width=b.width;this.canvas.height=b.height;this.ctx=this.canvas.getContext("2d");this.ctx.drawImage(b,0,0);this.pixels=this.ctx.getImageData(0,0,b.width,b.height);this.position=new TreePosition(0,0,0,b.width,b.height);this.tree=new Noeud(null,null,null,null,0,b.width-1,0,b.height-1,null,this.position,cptId);cptId++;for(var d=0;d<b.width*b.height*4;d+=4)this.tree.ajouterFeuille(new Feuille(d/4%b.width,
Math.floor(d/4/b.width),128>=this.pixels.data[d+3]?0:1));this.tree.compress();console.log("Arbre Construit "+this.tree.compterFeuilles()+" feuilles");this.setPosition=function(b,d,k){this.position.x=parseFloat(b);this.position.y=parseFloat(d);this.position.rad=parseFloat(k)};this.isCollisionWith=function(b){return this.tree.isCollisionWithNode(b.tree)}}else window.alert("Image non encore chargee")};