function f(a,b){return a[0]*b[1]-a[1]*b[0]}function l(a,b,c){this.x=a;this.y=b;this.value=c}function q(a,b){this.J=this.y=this.x=0;this.width=a;this.height=b}
function r(a,b,c,d,h,e,n){this.o=this.n=this.t=this.s=null;this.D=a;this.F=b;this.H=c;this.G=d;this.a=h;this.position=e;this.id=n;this.l=function(a){if(null!=this.a){var g=this.a;this.a=null;this.l(g);this.l(a)}else{var g=Math.round((this.D+this.F)/2),b=Math.round((this.H+this.G)/2);a.x<g?a.y<b?null==this.s?this.s=new r(this.D,g,this.H,b,a,this.position,this.id):this.s.l(a):null==this.n?this.n=new r(this.D,g,b,this.G,a,this.position,this.id):this.n.l(a):a.y<b?null==this.t?this.t=new r(g,this.F,this.H,
b,a,this.position,this.id):this.t.l(a):null==this.o?this.o=new r(g,this.F,b,this.G,a,this.position,this.id):this.o.l(a)}};this.q=function(){var a=[];null!=this.s&&a.push(this.s);null!=this.t&&a.push(this.t);null!=this.n&&a.push(this.n);null!=this.o&&a.push(this.o);return a};this.L=function(){if(null==this.a){var a=this.q();if(0<a.length){for(var g=0;g<a.length;g++)a[g].L();for(var b=!0,g=0;g<a.length;g++)null==a[g].a&&(b=!1);if(b){for(var g=a[0].a.value,c=1;c<a.length;c++)a[c].a.value!=g&&(b=!1);
b&&(this.o=this.n=this.t=this.s=null,this.a=new l(-1,-1,g))}}}};this.M=function(){if(null!=this.a)return 1;for(var a=this.q(),g=0,b=0;b<a.length;b++)g+=a[b].M();return g};this.O=function(){var a=Math.cos(this.position.J),b=Math.sin(this.position.J),c=this.D-this.position.width/2,s=this.F-this.position.width/2,d=this.H-this.position.height/2,e=this.G-this.position.height/2;return[[a*c-b*d+this.position.x+this.position.width/2,b*c+a*d+this.position.y+this.position.height/2],[a*c-b*e+this.position.x+
this.position.width/2,b*c+a*e+this.position.y+this.position.height/2],[a*s-b*e+this.position.x+this.position.width/2,b*s+a*e+this.position.y+this.position.height/2],[a*s-b*d+this.position.x+this.position.width/2,b*s+a*d+this.position.y+this.position.height/2]]};this.R=function(a){var b=this.O();a=a.O();for(var c=[[b[1][0]-b[0][0],b[1][1]-b[0][1]],[b[2][0]-b[1][0],b[2][1]-b[1][1]],[b[3][0]-b[2][0],b[3][1]-b[2][1]],[b[0][0]-b[3][0],b[0][1]-b[3][1]]],d=[[a[1][0]-a[0][0],a[1][1]-a[0][1]],[a[2][0]-a[1][0],
a[2][1]-a[1][1]],[a[3][0]-a[2][0],a[3][1]-a[2][1]],[a[0][0]-a[3][0],a[0][1]-a[3][1]]],e,h,m=0;4>m;m++){h=!0;for(var k=0;4>k;k++)if(e=[a[m][0]-b[k][0],a[m][1]-b[k][1]],0<c[k][0]*e[1]-c[k][1]*e[0]){h=!1;break}if(h)return!0}for(m=0;4>m;m++){h=!0;for(k=0;4>k;k++)if(e=[b[m][0]-a[k][0],b[m][1]-a[k][1]],0<d[k][0]*e[1]-d[k][1]*e[0]){h=!1;break}if(h)return!0}for(m=0;4>m;m++)for(k=0;4>k;k++){var c=b[m],p=b[(m+1)%4],d=a[k];e=a[(k+1)%4];h=[p[0]-c[0],p[1]-c[1]];var n=[e[0]-d[0],e[1]-d[1]],p=[p[0]-d[0],p[1]-d[1]],
H=[c[0]-d[0],c[1]-d[1]];if(0==f(h,n)?0:0>=f(h,[e[0]-c[0],e[1]-c[1]])*f(h,[d[0]-c[0],d[1]-c[1]])&&0>=f(n,p)*f(n,H))return!0}return!1};this.C=function(a){if(null!=this.a&&0==this.a.value||null!=a.a&&0==a.a.value||!this.R(a))return!1;if(null!=this.a&&null!=a.a)return!0;var b,c;if(null==this.a&null==a.a){c=this.q();a=a.q();b=!1;for(var d=0;d<c.length;d++)for(var e=0;e<a.length;e++)c[d].C(a[e])&&(b=!0);return b}if(null==this.a){c=this.q();b=!1;for(d=0;d<c.length;d++)a.C(c[d])&&(b=!0);return b}a=a.q();
b=!1;for(d=0;d<a.length;d++)this.C(a[d])&&(b=!0);return b}}var t=0;
function u(a){if(a.complete){this.canvas=document.createElement("canvas");this.canvas.width=a.width;this.canvas.height=a.height;this.N=this.canvas.getContext("2d");this.N.drawImage(a,0,0);this.S=this.N.getImageData(0,0,a.width,a.height);this.position=new q(a.width,a.height);this.v=new r(0,a.width-1,0,a.height-1,null,this.position,t);t++;for(var b=0;b<a.width*a.height*4;b+=4)this.v.l(new l(b/4%a.width,Math.floor(b/4/a.width),128>=this.S.data[b+3]?0:1));this.v.L();console.log("Arbre Construit "+this.v.M()+
" feuilles");this.P=function(a,b,h){this.position.x=parseFloat(a);this.position.y=parseFloat(b);this.position.J=parseFloat(h)};this.Q=function(){return this.v.C(v.v)}}else window.alert("Image non encore chargee")}VOITURE_LONGUEUR=5;VOLANT_INITIAL=-0.7;VOLANT_TIME=VOLANT_FINAL=0.7;ACCELERATEUR_FINAL=100;ACCELERATEUR_TIME=0.6;FREIN_FINAL=80;FREIN_TIME=0.4;STEPS=200;COEF_FROTEMENTS=7;V_MA=0.01;V_NULL=0.04;RENDER_STEPS=3;ZOOM=20;KEY_DOWN=40;KEY_UP=38;KEY_LEFT=37;KEY_RIGHT=39;
function w(a,b,c){this.value=0;this.r=a;this.p=b;this.time=c;this.K=1}function x(a,b,c,d,h,e,n,F,g,G){this.b=a;this.c=b;this.i=c;this.j=d;this.e=h;this.f=e;this.g=n;this.h=F;this.I=g;this.d=G}function y(a){a.value+=a.K*(a.p-a.r)/(STEPS*a.time);a.p>=a.r?a.value>a.p?a.value=a.p:a.value<a.r&&(a.value=a.r):a.value<a.p?a.value=a.p:a.value>a.r&&(a.value=a.r)}var z=[],A;for(A=0;128>A;A++)z[A]=0;
var B=0,C=new x(30,10,0,0,0,0,10,10+ZOOM*VOITURE_LONGUEUR,VOITURE_LONGUEUR,new function(a,b,c,d){this.k=a;this.A=b;this.B=c;this.m=d}(new w(VOLANT_INITIAL,VOLANT_FINAL,VOLANT_TIME),new w(0,ACCELERATEUR_FINAL,ACCELERATEUR_TIME),new w(0,FREIN_FINAL,FREIN_TIME),1)),D=new function(a,b,c,d){this.w=a;this.u=b;this.left=c;this.right=d}(0,0,0,0),E=new u(document.getElementById("car_image")),v=new u(document.getElementById("collMap_image"));v.P(0,0,0);
setInterval(function(){B++;0==B%STEPS&&(console.log("Tic"),B=0);var a=new x(parseFloat(C.b),parseFloat(C.c),parseFloat(C.i),parseFloat(C.j),parseFloat(C.e),parseFloat(C.f),parseFloat(C.g),parseFloat(C.h),parseFloat(C.I),C.d);a.e*a.e+a.f*a.f<V_MA&&(D.u&&(a.d.m=-1),D.w&&(a.d.m=1));var b=a.d,c=1==b.m?1:0;D.w&&c||D.u&&!c?y(b.A):b.A.value=0;D.u&&c||D.w&&!c?y(b.B):b.B.value=0;D.left&&(b.k.K=1,y(b.k));D.right&&(b.k.K=-1,y(b.k));b=a.b-a.g;c=a.c-a.h;c=0<c?Math.atan(b/c):Math.atan(b/c)+Math.PI;b=Math.sqrt(a.e*
a.e+a.f*a.f);a.e=a.d.m*b*Math.sin(c+a.d.k.value);a.f=a.d.m*b*Math.cos(c+a.d.k.value);var d,h,e;0==a.e&&0==a.f?c=b=e=0:(e=Math.sqrt(a.e*a.e+a.f*a.f),e<V_NULL?(c=b=e=0,a.e=0,a.f=0):(b=a.e/e,c=a.f/e));h=Math.sqrt((a.b-a.g)*(a.b-a.g)+(a.c-a.h)*(a.c-a.h));d=(a.b-a.g)/h;h=(a.c-a.h)/h;a.i=d*a.d.m*a.d.A.value;a.j=h*a.d.m*a.d.A.value;d=Math.pow(e,0.5);a.i-=d*b*a.d.B.value;a.j-=d*c*a.d.B.value;d=(1+Math.cos(a.d.k.value))/2*Math.pow(e,1);a.i-=COEF_FROTEMENTS*d*b;a.j-=COEF_FROTEMENTS*d*c;a.b+=(a.e+a.i/STEPS/
2)/STEPS;a.c+=(a.f+a.j/STEPS/2)/STEPS;a.e+=a.i/STEPS;a.f+=a.j/STEPS;c=Math.sqrt((a.b-a.g)*(a.b-a.g)+(a.c-a.h)*(a.c-a.h));b=(a.b-a.g)/c;c=(a.c-a.h)/c;a.g=a.b-a.I*b;a.h=a.c-a.I*c;b=0.48*ZOOM*a.b+0.52*ZOOM*a.g-88;c=0.48*ZOOM*a.c+0.52*ZOOM*a.h-85+45;e=a.b-a.g;d=a.c-a.h;E.P(b,c,-1*((0<d?Math.atan(e/d):Math.atan(e/d)+Math.PI)+Math.PI/2));E.Q()?(C.e=0,C.f=0,C.i=0,C.j=0):(C.b=a.b,C.c=a.c,C.e=a.e,C.f=a.f,C.i=a.i,C.j=a.j,C.g=a.g,C.h=a.h)},1E3/STEPS);
setInterval(function(){var a,b;a=0.48*ZOOM*C.b+0.52*ZOOM*C.g-88;b=0.48*ZOOM*C.c+0.52*ZOOM*C.h-85+45;var c,d;c=C.b-C.g;d=C.c-C.h;c=0<d?Math.atan(c/d):Math.atan(c/d)+Math.PI;document.getElementById("car").style.webkitTransform="translate("+a+"px, "+b+"px) rotate("+-1*(180*c/Math.PI+90)+"deg)";document.getElementById("roues").style.webkitTransform="translate("+a+"px, "+b+"px) rotate("+-1*(180*c/Math.PI+90)+"deg)";document.getElementById("RG").style.webkitTransform="rotate("+(180*-C.d.k.value/Math.PI+
90)+"deg)";document.getElementById("RD").style.webkitTransform="rotate("+(180*-C.d.k.value/Math.PI+90)+"deg)"},20);document.addEventListener("keydown",function(a){if(!z[a.keyCode]){switch(a.keyCode){case KEY_UP:D.w=1;break;case KEY_DOWN:D.u=1;break;case KEY_LEFT:D.left=1;break;case KEY_RIGHT:D.right=1}z[a.keyCode]=1}},!1);
document.addEventListener("keyup",function(a){z[a.keyCode]=0;switch(a.keyCode){case KEY_UP:D.w=0;break;case KEY_DOWN:D.u=0;break;case KEY_LEFT:D.left=0;break;case KEY_RIGHT:D.right=0}},!1);